### ISSUE TITLE
Define metadata type for Trustless HTTP Gateway Multicodec

### ISSUE THREAD

**Issue by hannahhoward** [ipni/go-libipni#21]
# What

Define a metadata type for the new multicodec defined here https://github.com/multiformats/multicodec/pull/321, support records publishing for this metadata type

# Implementation

My suggestion is for the time being, this metadata should simply be an empty struct until we identify any additional parameters required. The codec isn't really finished until https://github.com/ipfs/specs/pull/402 is merged, and I expect more things to change before it is.

**Comment by willscott** [comment]
agree it can be empty - the same as the current bitswap behavior.
for that, i don't believe any particular change is needed to support it, though we can provide a nice name in https://github.com/ipni/go-libipni/tree/main/metadata rather than making users use the `unknown` fallback wrapper.

**Comment by hannahhoward** [comment]
That'd be great!
