### ISSUE TITLE
Skip addr that failed to parse in Message.GetAddr()

### ISSUE THREAD

**Issue by MarcoPolo** [ipni/go-libipni#29]
In: https://github.com/ipni/go-libipni/blob/afe2d8ea45b86c2a22f756ee521741c8f99675e5/announce/message/message.go#L44

... and probably only return an error if all addrs failed to parse. This makes adding new transports easier and avoids having the caller fail if there was one way they could reach the peer.

**Comment by gammazero** [comment]
Seems like we still want an error when the addresses are structurally wrong.  Maybe it would be better to skip specific errors, like [this](https://github.com/multiformats/go-multiaddr/blob/master/codec.go#L79), instead of any errors. Otherwise, we might be hiding errors that should be fixed.

**Comment by gammazero** [comment]
@MarcoPolo Does #30 work as a fix for this?

**Comment by gammazero** [comment]
Fixed by #30
