### ISSUE TITLE
Modify `dhash_client` to be able to perform `/multihash` and `/metadata` lookups through the `dhstore` interface

### ISSUE THREAD

**Issue by ischasny** [ipni/go-libipni#52]
`dash_client` contains all logic for assembling a provider record from different pieces, including hashing, decryption, lookups and complicated bits like `ExtendedProviders`. Currently `dash_client` can perform `/multihash`, `/metadata` and `/provider` lookups over HTTP only. That needs changing for `dhfind` to be merged with `dhstore` because then `/multihash` and `/metadata` lookups will have to be performed through the [dhstore interface](https://github.com/ipni/dhstore/blob/main/dhstore.go#L17) instead.

Modify `dash_client` to be able to take in [dhstore interface](https://github.com/ipni/dhstore/blob/main/dhstore.go#L17) as a configuration option. If provided then `dash_client` should use it for `/metadata` and `/multihash` lookups but keep using `stiUrl` for `/providers`. Note that the `dhstore` interface is not in the `go-libipni` repository.

**Comment by ischasny** [comment]
I'd argue that the  logic inside the client is complex enough for us to not to duplicate it. We don't have to expose dhstore interface to go-libipni but use a proxy interface instead.

**Comment by gammazero** [comment]
What about refactoring the part that does the double-hashing and metadata lookup into a separate package, and then having both the DHashClient and DHFind/Store import that. Then DHashClient would not need to have any knowledge of DHStore instrfave (even a proxy interface), and DHFind/Store would not have to duplicate the dhouble-hash handling.

**Comment by ischasny** [comment]
I don't think that how lookup is done is a problem here. There is a corpus of logic such as hashing, decryption, assembling a record, skipping things if some parts aren't found, caching, extended providers that needs to be the same across all use cases. 

How the actual bytes get into it is secondary in my opinion - either via http, or from a database or from a test.

**Comment by gammazero** [comment]
I think I see what you mean, and I am OK moving forward with this. We can always refactor this later, and determine what the final IPNI client find interface(s) should look like.
